# Generated by Django 5.0.4 on 2024-05-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='authenticated',
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
