# Generated by Django 5.0.4 on 2024-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_authenticated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
